import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="p-2 border-b flex gap-4 items-center">
          <a href="/">Home</a>
          <a href="/notifications">🔔</a>
          <form action="/search/tasks" method="GET" className="ml-auto">
            <input
              type="text"
              name="q"
              placeholder="Search tasks..."
              className="border rounded px-2 py-1 text-sm"
            />
          </form>
        </nav>
        {children}
      </body>
    </html>
  );
}
