import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import AppShell from '@/components/layout/AppShell';
import LoopBuilder from '@/components/loop-builder';
import PushNotificationInitializer from '@/components/PushNotificationInitializer';
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased bg-[var(--color-background)]`}>
        <AppShell>{children}</AppShell>
        <LoopBuilder />
        <PushNotificationInitializer />
      </body>
    </html>
  );
}
