import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import LoopBuilder from '@/components/loop-builder';
import PushNotificationInitializer from '@/components/PushNotificationInitializer';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[var(--color-background)]`}>
        <div className="app-shell">
          <header className="app-header">
            <div className="app-header__branding">
              <span className="app-header__logo" aria-hidden>⬡</span>
              <span className="app-header__name">LoopTask</span>
            </div>
            <div className="app-header__actions" aria-label="Global navigation" />
          </header>
          <main className="app-main">{children}</main>
          <footer className="app-footer">
            <p>© {new Date().getFullYear()} LoopTask. All rights reserved.</p>
          </footer>
        </div>
        <LoopBuilder />
        <PushNotificationInitializer />
      </body>
    </html>
  );
}
